version: '3.7'
services:
    app:
      build: './app'
      container_name: 'app1'
      restart: 'always'
      expose:
        - 8000
#      env_file:
#        - .env
      environment:
        - "POSTGRES_DB=django_app"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_PASSWORD=test"
        - "POSTGRES_HOST=postgres"
      volumes:
        - type: 'bind'
          source: './volumes/app'
          target: '/app'
      depends_on:
        - "postgres"
        - "nginx"

    postgres:
      image: 'postgres'
      container_name: 'postgres1'
      restart: 'always'
      expose:
        - 5432
#      env_file:
#        - .env
      environment:
        - "POSTGRES_DB=django_app"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_PASSWORD=test"
      volumes:
        - type: 'bind'
          source: './volumes/dbdata'
          target: '/var/lib/postgresql/data'



    nginx:
      build: './nginx'
      container_name: 'nginx1'
      restart: 'always'
      ports:
        - '80:80'
      volumes:
        - type: 'bind'
          source: './volumes/media'
          target: '/app/media'
        - type: 'bind'
          source: './volumes/static'
          target: '/app/static'